/*
 * Copyright 2026 Project Montreal contributors
 *
 * SPDX-License-Identifier: CERN-OHL-P-2.0
 *
 * Project:       Montreal (RV32E SoC for Tiny Tapeout)
 *
 * Module:        uart_tx
 * Specification: Montreal Debug UART v0.1 (uarch/uart.adoc)
 * Version:       0.1.0
 * Authors:       Pouya Hatami <pouyahatami10@gmail.com>
 *
 * Description:   UART transmit engine
 *
 * Serialises one byte as an 8N1 frame: one start bit (low), eight data
 * bits least-significant first, and one stop bit (high). The line idles
 * high
 *
 * The bit period is generated by a counter producing a single-cycle
 * enable. No clock is gated or divided; the module remains in one clock
 * domain
 *
 * The length of that period comes from bit_period_i, which the bus
 * register block drives from the BITPERIOD register, so the baud rate can
 * be corrected after fabrication if the clock is not the one assumed at
 * reset. The value is compared every cycle and is not latched at the
 * start of a frame, so it must be held stable while busy_o is high:
 * changing it mid-frame stretches or truncates the period being timed
 *
 * This module has no knowledge of the register file, the bus or the
 * dump format. It is a shared resource driven by the reset banner
 * generator, the dump sequencer and the bus register block through the
 * same start / data / busy handshake
 *
 * A request arriving while a frame is in flight is ignored and its byte
 * is lost. drop_o pulses when that happens, so a caller that cares can
 * record it
 */

`include "config.svh"

module uart_tx (
  input logic clk_i,
  input logic rst_ni,

  input logic [UART_BIT_PERIOD_WIDTH-1:0] bit_period_i,

  input  logic                   start_i,
  input  logic [SLICE_WIDTH-1:0] data_i,
  output logic                   busy_o,
  output logic                   drop_o,

  output logic tx_o
);

  /* ------------------------------------------------------------------ *
   * Parameter checks                                                   *
   * ------------------------------------------------------------------ */

  /* The payload is eight bits because the 8N1 frame format says so, not
   * because the datapath is sliced eight bits wide. SLICE_WIDTH is
   * reused here only because it currently happens to be eight; the two
   * are eight for unrelated reasons and are free to diverge
   *
   * Neither check below costs hardware. They are duplicated because no
   * one form is honoured everywhere: Verilator evaluates the
   * elaboration-time $error under 'make lint', while simulators reach
   * the $fatal at time zero instead. Note that neither currently runs
   * in CI, which lints with Verible (a parser, so it elaborates
   * nothing) and otherwise runs only the regfile formal task */
  if (SLICE_WIDTH != 8) begin : gen_slice_width_check
    $error("uart_tx: SLICE_WIDTH must be 8; the 8N1 payload width is ",
        "fixed by the UART protocol and cannot follow the datapath");
  end

`ifndef SYNTHESIS
  initial begin : p_slice_width_check
    if (SLICE_WIDTH != 8) begin
      $fatal(1, "uart_tx: SLICE_WIDTH must be 8, got %0d", SLICE_WIDTH);
    end
  end
`endif

  /* ------------------------------------------------------------------ *
   * State encoding                                                     *
   * ------------------------------------------------------------------ */

  typedef enum logic [1:0] {
    TX_IDLE  = 2'b00,
    TX_START = 2'b01,
    TX_DATA  = 2'b10,
    TX_STOP  = 2'b11
  } tx_state_t;

  tx_state_t state_q;
  tx_state_t state_d;

  /* ------------------------------------------------------------------ *
   * Internal registers                                                 *
   * ------------------------------------------------------------------ */

  /* Counts clock cycles within one bit period */
  logic [UART_BIT_PERIOD_WIDTH-1:0] cycle_cnt_q;

  /* Counts data bits driven so far, 0 to 7 */
  logic [SLICE_SHIFT_WIDTH-1:0] bit_cnt_q;

  /* Index of the last data bit in a frame */
  localparam logic [SLICE_SHIFT_WIDTH-1:0] LAST_DATA_BIT = SLICE_WIDTH - 1;

  /* High while the last data bit of the frame is being driven */
  logic last_bit;

  assign last_bit = (bit_cnt_q == LAST_DATA_BIT);

  /* Holds the byte being transmitted, shifted right one bit per
   * shift_en pulse */
  logic [SLICE_WIDTH-1:0] shift_q;

  /* ------------------------------------------------------------------ *
   * Bit period generator                                               *
   * ------------------------------------------------------------------ */

  /* Single-cycle enable marking the end of a bit period
   *
   * bit_period_i is one less than the number of clock cycles in a bit
   * period, so the counter runs from zero to bit_period_i inclusive and
   * the comparison needs no adjustment. A programmed value of zero makes
   * every clock cycle a bit period; nothing here prevents it */
  logic shift_en;

  assign shift_en = (cycle_cnt_q == bit_period_i);

  /* Held clear in TX_IDLE so that the start bit always receives a full
   * bit period, regardless of when start_i arrives */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      cycle_cnt_q <= '0;
    end else if ((state_q == TX_IDLE) || shift_en) begin
      cycle_cnt_q <= '0;
    end else begin
      cycle_cnt_q <= cycle_cnt_q + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Next state selection                                               *
   * ------------------------------------------------------------------ */

  always_comb begin
    /* Otherwise stay in current state */
    state_d = state_q;

    unique case (state_q)
      /* Wait for a request */
      TX_IDLE: begin
        if (start_i) state_d = TX_START;
      end

      /* Drive the start bit for one bit period */
      TX_START: begin
        if (shift_en) state_d = TX_DATA;
      end

      /* Drive eight data bits, least significant first */
      TX_DATA: begin
        if (shift_en && last_bit) state_d = TX_STOP;
      end

      /* Drive the stop bit for one bit period */
      TX_STOP: begin
        if (shift_en) state_d = TX_IDLE;
      end

      default: state_d = TX_IDLE;
    endcase
  end

  /* ------------------------------------------------------------------ *
   * State register                                                     *
   * ------------------------------------------------------------------ */

  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      state_q <= TX_IDLE;
    end else begin
      state_q <= state_d;
    end
  end

  /* ------------------------------------------------------------------ *
   * Data path                                                          *
   * ------------------------------------------------------------------ */

  /* Loaded on acceptance, then shifted right once per bit period so
   * that bit 0 always carries the bit currently being driven */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      shift_q <= '0;
    /* A write arriving mid-frame will be dropped, silently */
    end else if ((state_q == TX_IDLE) && start_i) begin
      shift_q <= data_i;
    end else if ((state_q == TX_DATA) && shift_en) begin
      shift_q <= {1'b0, shift_q[SLICE_WIDTH-1:1]};
    end
  end

  /* Cleared outside TX_DATA so that every frame starts from bit 0 */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      bit_cnt_q <= '0;
    end else if (state_q != TX_DATA) begin
      bit_cnt_q <= '0;
    end else if (shift_en) begin
      bit_cnt_q <= bit_cnt_q + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Outputs                                                            *
   * ------------------------------------------------------------------ */

  assign busy_o = (state_q != TX_IDLE);

  /* Single-cycle pulse marking a request refused because a frame was
   * already in flight. The byte is lost: it is not stored anywhere and
   * the frame in progress is unaffected
   *
   * The condition is derived here rather than by the caller so that it
   * cannot drift from the acceptance rule in the data path above. The
   * bus register block latches it into the sticky DROPPED status bit */
  assign drop_o = start_i && busy_o;

  /* The line is driven from a register to keep the path to the pad
   * short. This delays the whole frame by one clock cycle. Every bit is
   * delayed equally, so each bit period remains exactly the programmed
   * length and the receiver is unaffected
   *
   * Reset drives the line high: a low idle line is indistinguishable
   * from a break condition (DR-UART-011) */
  logic tx_q;

  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      tx_q <= 1'b1;
    end else begin
      unique case (state_q)
        TX_IDLE:  tx_q <= 1'b1;
        TX_START: tx_q <= 1'b0;
        TX_DATA:  tx_q <= shift_q[0];
        TX_STOP:  tx_q <= 1'b1;
        default:  tx_q <= 1'b1;
      endcase
    end
  end

  assign tx_o = tx_q;

endmodule : uart_tx
