/*
 * Copyright 2026 Project Montreal contributors
 *
 * SPDX-License-Identifier: CERN-OHL-P-2.0
 *
 * Project:       Montreal (RV32E SoC for Tiny Tapeout)
 *
 * Module:        uart_tx
 * Specification: Montreal Debug UART v0.1 (uarch/uart.adoc)
 * Version:       0.1.0
 * Authors:       Pouya Hatami <pouyahatami10@gmail.com>
 *
 * Description:   UART transmit engine
 *
 * Serialises one byte as an 8N1 frame: one start bit (low), eight data
 * bits least-significant first, and one stop bit (high). The line idles
 * high
 *
 * The bit period is generated by a counter producing a single-cycle
 * enable. No clock is gated or divided; the module remains in one clock
 * domain
 *
 * This module has no knowledge of the register file, the bus or the
 * dump format. It is a shared resource driven by the reset banner
 * generator, the dump sequencer and the bus register block through the
 * same start / data / busy handshake
 */

`include "config.svh"

module uart_tx (
  input logic clk,
  input logic rst_n,

  input  logic                   start,
  input  logic [SLICE_WIDTH-1:0] data,
  output logic                   busy,

  output logic tx
);

  /* ------------------------------------------------------------------ *
   * State encoding                                                     *
   * ------------------------------------------------------------------ */

  typedef enum logic [1:0] {
    TX_IDLE  = 2'b00,
    TX_START = 2'b01,
    TX_DATA  = 2'b10,
    TX_STOP  = 2'b11
  } tx_state_t;

  tx_state_t state;
  tx_state_t next_state;

  /* ------------------------------------------------------------------ *
   * Internal registers                                                 *
   * ------------------------------------------------------------------ */

  /* Counts clock cycles within one bit period */
  logic [UART_BAUD_CNT_WIDTH-1:0] baud_cnt;

  /* Counts data bits driven so far, 0 to 7 */
  logic [SLICE_SHIFT_WIDTH-1:0] bit_cnt;

  /* High while the last data bit of the frame is being driven */
  logic last_bit;

  assign last_bit = (bit_cnt == SLICE_SHIFT_WIDTH'(SLICE_WIDTH - 1));

  /* Holds the byte being transmitted, shifted right one bit per
   * baud tick */
  logic [SLICE_WIDTH-1:0] shift;

  /* ------------------------------------------------------------------ *
   * Bit period generator                                               *
   * ------------------------------------------------------------------ */

  /* Single-cycle enable marking the end of a bit period */
  logic baud_tick;

  assign baud_tick = (baud_cnt == UART_BAUD_CNT_WIDTH'(UART_CLKS_PER_BIT - 1));

  /* Held clear in TX_IDLE so that the start bit always receives a full
   * bit period, regardless of when start arrives */
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      baud_cnt <= '0;
    end else if ((state == TX_IDLE) || baud_tick) begin
      baud_cnt <= '0;
    end else begin
      baud_cnt <= baud_cnt + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Next state selection                                               *
   * ------------------------------------------------------------------ */

  always_comb begin
    /* Otherwise stay in current state */
    next_state = state; 

    unique case (state)
      /* Wait for a request */
      TX_IDLE: begin
        if (start) next_state = TX_START;
      end

      /* Drive the start bit for one bit period */
      TX_START: begin
        if (baud_tick) next_state = TX_DATA;
      end

      /* Drive eight data bits, least significant first */
      TX_DATA: begin
        if (baud_tick && last_bit) next_state = TX_STOP;
      end

      /* Drive the stop bit for one bit period */
      TX_STOP: begin
        if (baud_tick) next_state = TX_IDLE;
      end

      default: next_state = TX_IDLE;
    endcase
  end

  /* ------------------------------------------------------------------ *
   * State register                                                     *
   * ------------------------------------------------------------------ */

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      state <= TX_IDLE;
    end else begin
      state <= next_state;
    end
  end

  /* ------------------------------------------------------------------ *
   * Data path                                                          *
   * ------------------------------------------------------------------ */

  /* Loaded on acceptance, then shifted right once per bit period so
   * that bit 0 always carries the bit currently being driven */
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      shift <= '0;
    end else if ((state == TX_IDLE) && start) begin
      shift <= data;
    end else if ((state == TX_DATA) && baud_tick) begin
      shift <= {1'b0, shift[SLICE_WIDTH-1:1]};
    end
  end

  /* Cleared outside TX_DATA so that every frame starts from bit 0 */
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      bit_cnt <= '0;
    end else if (state != TX_DATA) begin
      bit_cnt <= '0;
    end else if (baud_tick) begin
      bit_cnt <= bit_cnt + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Outputs                                                            *
   * ------------------------------------------------------------------ */

  assign busy = (state != TX_IDLE);

  /* The output is registered to keep the path to the pad short. This
   * delays the whole frame by one clock cycle. Every bit is delayed
   * equally, so each bit period remains exactly UART_CLKS_PER_BIT
   * cycles and the receiver is unaffected
   *
   * Reset drives the line high: a low idle line is indistinguishable
   * from a break condition (DR-UART-011) */
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      tx <= 1'b1;
    end else begin
      unique case (state)
        TX_IDLE:  tx <= 1'b1;
        TX_START: tx <= 1'b0;
        TX_DATA:  tx <= shift[0];
        TX_STOP:  tx <= 1'b1;
        default:  tx <= 1'b1;
      endcase
    end
  end

endmodule 
