/*
 * Copyright 2026 Project Montreal contributors
 *
 * SPDX-License-Identifier: CERN-OHL-P-2.0
 *
 * Project:       Montreal (RV32E SoC for Tiny Tapeout)
 *
 * Module:        uart_tx
 * Specification: Montreal Debug UART v0.1 (uarch/uart.adoc)
 * Version:       0.1.0
 * Authors:       Pouya Hatami <pouyahatami10@gmail.com>
 *
 * Description:   UART transmit engine
 *
 * Serialises one byte as an 8N1 frame: one start bit (low), eight data
 * bits least-significant first, and one stop bit (high). The line idles
 * high
 *
 * The bit period is generated by a counter producing a single-cycle
 * enable. No clock is gated or divided; the module remains in one clock
 * domain
 *
 * This module has no knowledge of the register file, the bus or the
 * dump format. It is a shared resource driven by the reset banner
 * generator, the dump sequencer and the bus register block through the
 * same start / data / busy handshake
 */

`include "config.svh"

module uart_tx (
  input logic clk_i,
  input logic rst_ni,

  input  logic                   start_i,
  input  logic [SLICE_WIDTH-1:0] data_i,
  output logic                   busy_o,

  output logic tx_o
);

  /* ------------------------------------------------------------------ *
   * State encoding                                                     *
   * ------------------------------------------------------------------ */

  typedef enum logic [1:0] {
    TX_IDLE  = 2'b00,
    TX_START = 2'b01,
    TX_DATA  = 2'b10,
    TX_STOP  = 2'b11
  } tx_state_t;

  tx_state_t state_q;
  tx_state_t state_d;

  /* ------------------------------------------------------------------ *
   * Internal registers                                                 *
   * ------------------------------------------------------------------ */

  /* Counts clock cycles within one bit period */
  logic [UART_BAUD_CNT_WIDTH-1:0] baud_cnt_q;

  /* Counts data bits driven so far, 0 to 7 */
  logic [SLICE_SHIFT_WIDTH-1:0] bit_cnt_q;

  /* Index of the last data bit in a frame */
  localparam logic [SLICE_SHIFT_WIDTH-1:0] LAST_DATA_BIT = SLICE_WIDTH - 1;

  /* High while the last data bit of the frame is being driven */
  logic last_bit;

  assign last_bit = (bit_cnt_q == LAST_DATA_BIT);

  /* Holds the byte being transmitted, shifted right one bit per
   * shift_en pulse */
  logic [SLICE_WIDTH-1:0] shift_q;

  /* ------------------------------------------------------------------ *
   * Bit period generator                                               *
   * ------------------------------------------------------------------ */

  /* Final baud counter value within a bit period */
  localparam logic [UART_BAUD_CNT_WIDTH-1:0] LAST_BAUD_CNT =
      UART_CLKS_PER_BIT - 1;

  /* Single-cycle enable marking the end of a bit period */
  logic shift_en;

  assign shift_en = (baud_cnt_q == LAST_BAUD_CNT);

  /* Held clear in TX_IDLE so that the start bit always receives a full
   * bit period, regardless of when start_i arrives */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      baud_cnt_q <= '0;
    end else if ((state_q == TX_IDLE) || shift_en) begin
      baud_cnt_q <= '0;
    end else begin
      baud_cnt_q <= baud_cnt_q + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Next state selection                                               *
   * ------------------------------------------------------------------ */

  always_comb begin
    /* Otherwise stay in current state */
    state_d = state_q;

    unique case (state_q)
      /* Wait for a request */
      TX_IDLE: begin
        if (start_i) state_d = TX_START;
      end

      /* Drive the start bit for one bit period */
      TX_START: begin
        if (shift_en) state_d = TX_DATA;
      end

      /* Drive eight data bits, least significant first */
      TX_DATA: begin
        if (shift_en && last_bit) state_d = TX_STOP;
      end

      /* Drive the stop bit for one bit period */
      TX_STOP: begin
        if (shift_en) state_d = TX_IDLE;
      end

      default: state_d = TX_IDLE;
    endcase
  end

  /* ------------------------------------------------------------------ *
   * State register                                                     *
   * ------------------------------------------------------------------ */

  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      state_q <= TX_IDLE;
    end else begin
      state_q <= state_d;
    end
  end

  /* ------------------------------------------------------------------ *
   * Data path                                                          *
   * ------------------------------------------------------------------ */

  /* Loaded on acceptance, then shifted right once per bit period so
   * that bit 0 always carries the bit currently being driven */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      shift_q <= '0;
    end else if ((state_q == TX_IDLE) && start_i) begin
      shift_q <= data_i;
    end else if ((state_q == TX_DATA) && shift_en) begin
      shift_q <= {1'b0, shift_q[SLICE_WIDTH-1:1]};
    end
  end

  /* Cleared outside TX_DATA so that every frame starts from bit 0 */
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      bit_cnt_q <= '0;
    end else if (state_q != TX_DATA) begin
      bit_cnt_q <= '0;
    end else if (shift_en) begin
      bit_cnt_q <= bit_cnt_q + 1'b1;
    end
  end

  /* ------------------------------------------------------------------ *
   * Outputs                                                            *
   * ------------------------------------------------------------------ */

  assign busy_o = (state_q != TX_IDLE);

  /* The line is driven from a register to keep the path to the pad
   * short. This delays the whole frame by one clock cycle. Every bit is
   * delayed equally, so each bit period remains exactly
   * UART_CLKS_PER_BIT cycles and the receiver is unaffected
   *
   * Reset drives the line high: a low idle line is indistinguishable
   * from a break condition (DR-UART-011) */
  logic tx_q;

  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      tx_q <= 1'b1;
    end else begin
      unique case (state_q)
        TX_IDLE:  tx_q <= 1'b1;
        TX_START: tx_q <= 1'b0;
        TX_DATA:  tx_q <= shift_q[0];
        TX_STOP:  tx_q <= 1'b1;
        default:  tx_q <= 1'b1;
      endcase
    end
  end

  assign tx_o = tx_q;

endmodule : uart_tx
